### PR TITLE
Add more rust target explanations

### PR DESCRIPTION
**Pull request by utzig**

### CODE REVIEW

**Comment by caspermeijn** [comment]
Why did you change the TARGET variable? Did you test that value? It doesn't seem to build for me, but I could do something wrong. 
If you do want to change it, you should change the `rustup` command as well.

I want to do some kind of mapping in the future, so that the mynewt compiler selection also triggers the rust compiler selection. But I don't know how to do that yet ;-)

**Comment by utzig** [comment]
> Why did you change the TARGET variable? Did you test that value? It doesn't seem to build for me, but I could do something wrong.

I had tested it on another MCU which is also Cortex-M4, but now I did on nrf52840 as well and it works. I updated this PR so that the shell script auto-detects which Cortex type is being used and sets the proper TARGET.

> If you do want to change it, you should change the `rustup` command as well.

Done (in a way!).

Why don't you submit a PR to https://github.com/apache/mynewt-core adding a new app, say `rust-blinky`? That would make it easier to colaborate then working on documentation! :-P

**Comment by caspermeijn** [comment]
Yes, that was what I was looking for! Now only the `emphasize-lines` needs an update.

Well, my idea was to keep the tutorial as a simplified explanation of how it works and then build towards a package that takes care of all this kind of stuff. 

For example a next tutorial I want to show how to convert the unsafe api to a rust api for GPIO and then point to a package with completed conversions. 

Now that I think about it, a rust-blinky app does matches this description as well.

The only problem is that I think the apps in core are not discoverable. I mostly used the tutorials for learning, because I didn't know the existence of the core apps.

**Comment by utzig** [comment]
> Yes, that was what I was looking for! Now only the `emphasize-lines` needs an update.

Done.

**Comment by caspermeijn** [comment]
LGTM

**Pull request merged**
